# Generated by Django 4.2.1 on 2023-06-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2, verbose_name='State (abbreviation)')),
                ('year_visited', models.IntegerField(verbose_name='If visited, what year')),
                ('highlights', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'Trail'), ('S', 'Scenic Drive'), ('C', 'Camp'), ('V', 'Viewpoints')], default='T', max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('comments', models.TextField(max_length=250)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.park')),
            ],
        ),
    ]
