# Generated by Django 4.2.1 on 2023-06-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='year_visited',
            field=models.IntegerField(blank=True, verbose_name='If visited, what year'),
        ),
    ]
