# Generated by Django 4.2.2 on 2023-06-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_photo_delete_parkphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='ActivityPhoto',
        ),
    ]
