# Generated by Django 4.2.2 on 2023-06-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_parkphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('T', 'Trail'), ('S', 'Scenic Drive'), ('C', 'Camp'), ('V', 'Viewpoint')], default='T', max_length=1),
        ),
    ]
