# Generated by Django 4.2.3 on 2023-07-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(choices=[('T', 'Trail'), ('S', 'Scenic Drive'), ('C', 'Camp'), ('V', 'Viewpoint')], default='T', max_length=100),
        ),
    ]
