# Generated by Django 4.2.3 on 2023-07-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_park_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='state',
        ),
        migrations.AddField(
            model_name='park',
            name='url',
            field=models.CharField(default='https://www.nps.gov/common/uploads/structured_data/3C7B45AE-1DD8-B71B-0B7EE131C7DFC2F5.jpg', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(choices=[('acad', 'Acadia National Park, ME'), ('arch', 'Arches National Park, UT'), ('badl', 'Badlands National Park, SD'), ('bibe', 'Big Bend National Park, TX'), ('bisc', 'Biscayne National Park, FL'), ('blca', 'Black Canyon Of The Gunnison National Park, CO'), ('brca', 'Bryce Canyon National Park, UT'), ('cany', 'Canyonlands National Park, UT'), ('care', 'Capitol Reef National Park, UT'), ('cave', 'Carlsbad Caverns National Park, NM'), ('chis', 'Channel Islands National Park, CA'), ('cong', 'Congaree National Park, SC'), ('crla', 'Crater Lake National Park, OR'), ('cuva', 'Cuyahoga Valley National Park, OH'), ('deva', 'Death Valley National Park, CA,NV'), ('drto', 'Dry Tortugas National Park, FL'), ('ever', 'Everglades National Park, FL'), ('jeff', 'Gateway Arch National Park, MO'), ('glac', 'Glacier National Park, MT'), ('grca', 'Grand Canyon National Park, AZ'), ('grte', 'Grand Teton National Park, WY'), ('grba', 'Great Basin National Park, NV'), ('grsm', 'Great Smoky Mountains National Park, NC,TN'), ('gumo', 'Guadalupe Mountains National Park, TX'), ('hale', 'Haleakalā National Park, HI'), ('havo', 'Hawaiʻi Volcanoes National Park, HI'), ('hosp', 'Hot Springs National Park, AR'), ('indu', 'Indiana Dunes National Park, IN'), ('isro', 'Isle Royale National Park, MI'), ('jotr', 'Joshua Tree National Park, CA'), ('kefj', 'Kenai Fjords National Park, AK'), ('kova', 'Kobuk Valley National Park, AK'), ('lavo', 'Lassen Volcanic National Park, CA'), ('maca', 'Mammoth Cave National Park, KY'), ('meve', 'Mesa Verde National Park, CO'), ('mora', 'Mount Rainier National Park, WA'), ('noca', 'North Cascades National Park, WA'), ('olym', 'Olympic National Park, WA'), ('pefo', 'Petrified Forest National Park, AZ'), ('pinn', 'Pinnacles National Park, CA'), ('romo', 'Rocky Mountain National Park, CO'), ('sagu', 'Saguaro National Park, AZ'), ('shen', 'Shenandoah National Park, VA'), ('thro', 'Theodore Roosevelt National Park, ND'), ('viis', 'Virgin Islands National Park, VI'), ('voya', 'Voyageurs National Park, MN'), ('whsa', 'White Sands National Park, NM'), ('wica', 'Wind Cave National Park, SD'), ('yell', 'Yellowstone National Park, ID,MT,WY'), ('yose', 'Yosemite National Park, CA'), ('zion', 'Zion National Park, UT')], default='acad', max_length=100),
        ),
    ]
