# Generated by Django 4.2.3 on 2023-07-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_park_state_park_url_alter_park_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
