# Generated by Django 4.2.3 on 2023-07-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_park_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=250)),
            ],
        ),
    ]
