# Generated by Django 4.2.3 on 2023-07-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_park_national_park_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='national_park_id',
            new_name='national_park',
        ),
    ]
