# Generated by Django 4.2.3 on 2023-07-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_rename_national_park_id_park_national_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
