# Generated by Django 4.2.3 on 2023-07-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_park_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='url',
        ),
    ]
