# Generated by Django 4.2.3 on 2023-07-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_remove_park_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NationalPark',
            new_name='NPS',
        ),
        migrations.RenameField(
            model_name='park',
            old_name='national_park',
            new_name='nps',
        ),
    ]
